export enum EnvVarNames {
  AUTHORISED_USERS = "AUTHORISED_USERS",
  AVAILABLE_CHANNELS = "AVAILABLE_CHANNELS",
  SOURCE_HOST = "SOURCE_HOST",
  TWITCH_INJEST = "TWITCH_INJEST",
  TWITCH_STREAM_KEY = "TWITCH_STREAM_KEY",
  BOT_USERNAME = "BOT_USERNAME",
  OAUTH_TOKEN = "OAUTH_TOKEN",
  LOG_LEVEL = "LOG_LEVEL",
  REMINDER_DIFFERENCE = "REMINDER_DIFFERENCE",
  STOP_TIME = "STOP_TIME",
  FFMPEG_LOG_LEVEL = "FFMPEG_LOG_LEVEL",
  NODE_ENV = "NODE_ENV",
}
